# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Deploy to ACM Server

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    secrets:
        FTP_HOSTNAME:
            required: True
        FTP_USERNAME:
            required: True
        FTP_PASSWORD:
            required: True

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
        with:
          ruby-version: '3.0' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Deploy HTML pages to website
        uses: sebastianpopp/ftp-action@releases/v2
        with:
            host: ${{ secrets.FTP_HOSTNAME }}
            user: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            localDir: "./_site/"
            remoteDir: "."
            forceSsl: true

      - name: Make PDF of schedule
        uses: misaelnieto/web_to_pdf_action@master
        with:
            webPageURL: https://2023.jcdl.org/program/schedule-printable/
            outputFile: ./_site/assets/downloads/schedule-printable.pdf
            usePuppeteer: true
            useScreen: false
            pdfOptions: '{"format": "Letter", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}, "displayHeaderFooter": false, "printBackground": true}'

      - name: Deploy PDF of schedule to website
        uses: sebastianpopp/ftp-action@releases/v2
        with:
            host: ${{ secrets.FTP_HOSTNAME }}
            user: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            localDir: "./_site/assets/downloads/"
            remoteDir: "./assets/downloads/"
            forceSsl: true

#   We encountered this bug in SamKirkland's FTP-Deploy-Action,
#   see: https://github.com/SamKirkland/FTP-Deploy-Action/issues/322
#        uses: SamKirkland/FTP-Deploy-Action@4.3.3
#        with:
#          server: ${{ secrets.FTP_HOSTNAME }}
#          username: ${{ secrets.FTP_USERNAME }}
#          password: ${{ secrets.FTP_PASSWORD }}
#          local-dir: ./_site/
#          dry-run: false
#          security: loose
#          protocol: ftps
